name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Convert owner name to lowercase
      - name: Set lowercase owner
        run: echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ env.OWNER_LOWER }}/francisapp:latest

      # Step 5: Push Docker image
      - name: Push Docker image
        run: docker push ghcr.io/${{ env.OWNER_LOWER }}/francisapp:latest
