name: Build and Push Docker Image

on:
  push:
   branches:
    - main

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Log in to Github Container Registry
      uses: docker/login-action@v2
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker Image
      run: |
        owner_lower=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${owner_lower}/francisapp:latest .
    
    - name: Push the Docker Image
      run: |
        owner_lower=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/${owner_lower}/francisapp:latest 